### PR TITLE
edrixs recipe is now working

### PR DESCRIPTION
**Pull request by shenmidelin**
Updates:
--------
- Use source file from PyPi, edrixs-0.0.4.tar.gz
- Remove setup.py.patch file
- Copy executables src/*.x to conda $PREFIX/bin folder

gfortran can not work with MKL, so we need to install edrixs by:

`conda install nomkl edrixs`

otherwise, somehow, conda will link to MKL, not libopenblas.

I have tested several examples, both python and fortran parts can work very well. MPI is also working  very well. No problems in this debian OS so far.

### CODE REVIEW

**Comment by mrakitin** [comment]
By the way, `edrixs` may have a `nomkl` dependency in the `run` section, so that you don't have to add it in the install command.

**Comment by shenmidelin** [comment]
Yes, that will be a good idea, thank you!

**Review by mrakitin — APPROVED** [review]
Great job! Thank you @shenmidelin.

**Comment by mrakitin** [comment]
xref https://github.com/NSLS-II/lightsource2-recipes/pull/742.

**Pull request merged**
